---

- hosts: all
  become: true
  pre_tasks:

    - name: install dnf
      tags: always
      yum:
        name:
          - dnf
        state: latest
      when: ansible_distribution in ["CentOS"]  

    - name: update repo cache (CentOS)
      dnf:
        update_cache: yes
      changed_when: false
      when: ansible_distribution in ["CentOS"]

    - name: update repo cache (Ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: all
  become: true
  roles:
    - base
- hosts: workstations
  become: true
  roles:
    - workstations
- hosts: web_servers
  become: true
  roles:
    - web_servers
- hosts: db_servers
  become: true
  roles:
    - db_servers
