- name: install apache and php packages
  tags: apache, httpd, php
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
  
- name: copy default html file fo site
  tags: apache, apache2
  copy:
    src: default-site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: start apache2
  tags: apache, Ubuntu
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
